version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: google.golang.org/grpc
    versions:
    - 1.35.0
    - 1.36.0
    - 1.36.1
  - dependency-name: github.com/maxatome/go-testdeep
    versions:
    - 1.8.0
    - 1.9.0
    - 1.9.1
  - dependency-name: github.com/sirupsen/logrus
    versions:
    - 1.7.1
    - 1.8.0
  - dependency-name: github.com/spf13/cobra
    versions:
    - 1.1.2
  - dependency-name: github.com/onsi/gomega
    versions:
    - 1.10.4
    - 1.10.5
  - dependency-name: github.com/hashicorp/go-memdb
    versions:
    - 1.3.1
  - dependency-name: golang.org/x/text
    versions:
    - 0.3.5
  - dependency-name: github.com/grpc-ecosystem/go-grpc-middleware
    versions:
    - 1.2.2
