# https://goreleaser.com/customization/
builds:
  - id: client
    binary: users-cli
    main: ./client/main.go
    goos: [freebsd, windows, linux, darwin]
    goarch: [amd64, arm, arm64]
    goarm: [6, 7]
    ignore:
      - { goos: darwin, goarch: 386 }
      - { goos: linux, goarch: arm, goarm: 7 }

  - id: server
    binary: users-server
    main: ./server/main.go
    goos: [freebsd, windows, linux, darwin]
    goarch: [amd64, arm, arm64]
    goarm: [6, 7]
    ignore:
      - { goos: darwin, goarch: 386 }
      - { goos: linux, goarch: arm, goarm: 7 }

archives:
  - id: client
    builds: [client]
    format: binary
  - id: server
    builds: [server]
    format: binary
