# https://goreleaser.com/customization/
builds:
  - id: client
    binary: users-cli
    main: ./cmd/users-cli/main.go
    goos: [windows, linux, darwin]
    goarch: [amd64]

  - id: server
    binary: users-server
    main: ./cmd/users-server/main.go
    goos: [windows, linux, darwin]
    goarch: [amd64]

archives:
  - id: client
    builds: [client]
    format: binary
  - id: server
    builds: [server]
    format: binary
