apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "users-grpc.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "users-grpc.name" . }}
    helm.sh/chart: {{ include "users-grpc.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "users-grpc.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "users-grpc.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - users-server
            - --reflection
            - --logfmt=json
            - --address=0.0.0.0:8000
            - -v
            {{- if .Values.tls.enabled }}
            - --tls
            - --tls-cert-file=/cert/tls.crt
            - --tls-key-file=/cert/tls.key
            {{- end }}
          ports:
            - name: grpc
              containerPort: 8000
              protocol: TCP
          readinessProbe:
            exec:
              command:
              - grpc-health-probe
              - -addr=:8000
              {{- if .Values.tls.enabled }}
              # -tls-no-verify is due to the fact that we reach the server
              # from an address that isn't in the cert's SANs.
              - -tls
              - -tls-no-verify
              {{- end }}
            initialDelaySeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.tls.enabled }}
          volumeMounts:
            - name: tls
              mountPath: /cert
              readOnly: true
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if .Values.tls.enabled }}
      volumes:
        - name: tls
          secret:
            secretName: {{ .Values.tls.secretName | quote }}
            defaultMode: 0400
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
    {{- end }}
