apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "users-grpc.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "users-grpc.name" . }}
    helm.sh/chart: {{ include "users-grpc.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "users-grpc.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "users-grpc.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - users-server
          - --logfmt=json
          - --address=0.0.0.0:8000
          - -v
          ports:
            - name: grpc
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            exec:
              command: ["/bin/grpc-health-probe", "-addr=:8000"]
            initialDelaySeconds: 10
          readinessProbe:
            exec:
              command: ["/bin/grpc-health-probe", "-addr=:8000"]
            initialDelaySeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
