---
# Source: users-grpc/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: users-grpc
  labels:
    app.kubernetes.io/name: users-grpc
    helm.sh/chart: users-grpc-0.1.0
    app.kubernetes.io/instance: users-grpc
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: users-grpc
    app.kubernetes.io/instance: users-grpc
---
# Source: users-grpc/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-grpc
  labels:
    app.kubernetes.io/name: users-grpc
    helm.sh/chart: users-grpc-0.1.0
    app.kubernetes.io/instance: users-grpc
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: users-grpc
      app.kubernetes.io/instance: users-grpc
  template:
    metadata:
      labels:
        app.kubernetes.io/name: users-grpc
        app.kubernetes.io/instance: users-grpc
    spec:
      containers:
        - name: users-grpc
          image: "maelvls/users-grpc:latest"
          imagePullPolicy: IfNotPresent
          args:
          - --logfmt=json
          - --address=0.0.0.0:8000
          ports:
            - name: grpc
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            exec:
              command: ["/bin/grpc-health-probe", "-addr=:8000"]
            initialDelaySeconds: 10
          readinessProbe:
            exec:
              command: ["/bin/grpc-health-probe", "-addr=:8000"]
            initialDelaySeconds: 5
          resources:
            {}
---
# Source: users-grpc/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "users-grpc-test-connection"
  labels:
    app.kubernetes.io/name: users-grpc
    helm.sh/chart: users-grpc-0.1.0
    app.kubernetes.io/instance: users-grpc
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: grpc-health-probe
      image: maelvls/users-grpc
      command: ['grpc-health-probe']
      args:  ['-addr=users-grpc:8000']
  restartPolicy: Never
